/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVidrosRouteImport } from './routes/_authenticated/vidros'
import { Route as AuthenticatedVendasRouteImport } from './routes/_authenticated/vendas'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated/producao'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedPerfisRouteImport } from './routes/_authenticated/perfis'
import { Route as AuthenticatedObrasRouteImport } from './routes/_authenticated/obras'
import { Route as AuthenticatedMateriaisRouteImport } from './routes/_authenticated/materiais'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedComercialRouteImport } from './routes/_authenticated/comercial'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedAcessoriosRouteImport } from './routes/_authenticated/acessorios'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVidrosRoute = AuthenticatedVidrosRouteImport.update({
  id: '/vidros',
  path: '/vidros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVendasRoute = AuthenticatedVendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfisRoute = AuthenticatedPerfisRouteImport.update({
  id: '/perfis',
  path: '/perfis',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasRoute = AuthenticatedObrasRouteImport.update({
  id: '/obras',
  path: '/obras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMateriaisRoute = AuthenticatedMateriaisRouteImport.update({
  id: '/materiais',
  path: '/materiais',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComercialRoute = AuthenticatedComercialRouteImport.update({
  id: '/comercial',
  path: '/comercial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcessoriosRoute = AuthenticatedAcessoriosRouteImport.update({
  id: '/acessorios',
  path: '/acessorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acessorios': typeof AuthenticatedAcessoriosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vidros': typeof AuthenticatedVidrosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acessorios': typeof AuthenticatedAcessoriosRoute
  '/clientes': typeof AuthenticatedClientesRoute
  '/comercial': typeof AuthenticatedComercialRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/materiais': typeof AuthenticatedMateriaisRoute
  '/obras': typeof AuthenticatedObrasRoute
  '/perfis': typeof AuthenticatedPerfisRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/vendas': typeof AuthenticatedVendasRoute
  '/vidros': typeof AuthenticatedVidrosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/acessorios': typeof AuthenticatedAcessoriosRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRoute
  '/_authenticated/comercial': typeof AuthenticatedComercialRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/materiais': typeof AuthenticatedMateriaisRoute
  '/_authenticated/obras': typeof AuthenticatedObrasRoute
  '/_authenticated/perfis': typeof AuthenticatedPerfisRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/vendas': typeof AuthenticatedVendasRoute
  '/_authenticated/vidros': typeof AuthenticatedVidrosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acessorios'
    | '/clientes'
    | '/comercial'
    | '/dashboard'
    | '/financeiro'
    | '/materiais'
    | '/obras'
    | '/perfis'
    | '/pipeline'
    | '/producao'
    | '/vendas'
    | '/vidros'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/acessorios'
    | '/clientes'
    | '/comercial'
    | '/dashboard'
    | '/financeiro'
    | '/materiais'
    | '/obras'
    | '/perfis'
    | '/pipeline'
    | '/producao'
    | '/vendas'
    | '/vidros'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/acessorios'
    | '/_authenticated/clientes'
    | '/_authenticated/comercial'
    | '/_authenticated/dashboard'
    | '/_authenticated/financeiro'
    | '/_authenticated/materiais'
    | '/_authenticated/obras'
    | '/_authenticated/perfis'
    | '/_authenticated/pipeline'
    | '/_authenticated/producao'
    | '/_authenticated/vendas'
    | '/_authenticated/vidros'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vidros': {
      id: '/_authenticated/vidros'
      path: '/vidros'
      fullPath: '/vidros'
      preLoaderRoute: typeof AuthenticatedVidrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas': {
      id: '/_authenticated/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof AuthenticatedVendasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfis': {
      id: '/_authenticated/perfis'
      path: '/perfis'
      fullPath: '/perfis'
      preLoaderRoute: typeof AuthenticatedPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras': {
      id: '/_authenticated/obras'
      path: '/obras'
      fullPath: '/obras'
      preLoaderRoute: typeof AuthenticatedObrasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materiais': {
      id: '/_authenticated/materiais'
      path: '/materiais'
      fullPath: '/materiais'
      preLoaderRoute: typeof AuthenticatedMateriaisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comercial': {
      id: '/_authenticated/comercial'
      path: '/comercial'
      fullPath: '/comercial'
      preLoaderRoute: typeof AuthenticatedComercialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acessorios': {
      id: '/_authenticated/acessorios'
      path: '/acessorios'
      fullPath: '/acessorios'
      preLoaderRoute: typeof AuthenticatedAcessoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcessoriosRoute: typeof AuthenticatedAcessoriosRoute
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRoute
  AuthenticatedComercialRoute: typeof AuthenticatedComercialRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedMateriaisRoute: typeof AuthenticatedMateriaisRoute
  AuthenticatedObrasRoute: typeof AuthenticatedObrasRoute
  AuthenticatedPerfisRoute: typeof AuthenticatedPerfisRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedVendasRoute: typeof AuthenticatedVendasRoute
  AuthenticatedVidrosRoute: typeof AuthenticatedVidrosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcessoriosRoute: AuthenticatedAcessoriosRoute,
  AuthenticatedClientesRoute: AuthenticatedClientesRoute,
  AuthenticatedComercialRoute: AuthenticatedComercialRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedMateriaisRoute: AuthenticatedMateriaisRoute,
  AuthenticatedObrasRoute: AuthenticatedObrasRoute,
  AuthenticatedPerfisRoute: AuthenticatedPerfisRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedVendasRoute: AuthenticatedVendasRoute,
  AuthenticatedVidrosRoute: AuthenticatedVidrosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
